version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      REACT_APP_URL: http://backend:4000
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
